variables:
  DOCKER_IMAGE: roohmeiy/todo-app-nodejs
  HELM_CHART_PATH: helm/todo-app-chart/values.yaml
  IMAGE_TAG: $CI_PIPELINE_ID # Use pipeline ID as a unique tag

stages:
  - test
  - build
  - update-helm

# Test stage (manual trigger)
test:
  stage: test
  image: node:18
  script:
    - chmod -R 755 node_modules/.bin
    - chmod +x ./node_modules/.bin/*
    - npm install
    - npx eslint . --ext .js --no-error-on-unmatched-pattern || true
    - npm test || true
    - npm audit || true
  rules:
    - if: $CI_COMMIT_BRANCH
      when: manual

# Build and push Docker image
build-and-push:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo "$DOCKER_PERSONAL_ACCESS_TOKEN" | docker login -u roohmeiy --password-stdin
  script:
    - docker build -t $DOCKER_IMAGE:$IMAGE_TAG .
    - docker push $DOCKER_IMAGE:$IMAGE_TAG
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        - "**/*"
        - "!${HELM_CHART_PATH}"  # Exclude Helm chart changes
  needs:
    - test

# Update the Helm chart with the new tag
update-helm-chart:
  stage: update-helm
  image: alpine:latest
  before_script:
    - apk add --no-cache git
  script:
    - git config --global user.email "roomeiy@gmail.com"
    - git config --global user.name "Payal Sharma"
    - 'sed -i "s/tag:.*/tag: $IMAGE_TAG/" $HELM_CHART_PATH'
    - git add $HELM_CHART_PATH
    - |
      git commit -m "Update image tag in Helm chart to $IMAGE_TAG [skip ci]"
      # Only push if there are changes to commit
      if [ $? -eq 0 ]; then
        git push "https://oauth2:${GITLAB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git" HEAD:$CI_COMMIT_BRANCH
      fi
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        - "**/*"
        - "!${HELM_CHART_PATH}"  # Exclude Helm chart changes
  needs:
    - build-and-push
