apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: todo-app-ns
  name: argocd-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets", "deployments", "replicasets"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    verbs: ["get", "list", "create", "update", "delete"]
