# Default values for todo-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: roohmeiy/todo-app-nodejs
  imagePullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "12609889823"

