name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      # - 'helm/**'
      - 'k8s/**'
      - 'README.md'
  push:
    branches:
      - main
    paths-ignore:
      # - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: roohmeiy
          password: ${{ secrets.DOCKER_PERSONAL_ACCESS_TOKEN }}

      - name: Build and Push action
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: roohmeiy/todo-app-nodejs:${{ github.run_id }} 

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update tag in Helm chart
        run: |
          sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/todo-app-chart/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "roohmeiy@gmail.com"
          git config --global user.name "Payal Sharma"
          git add helm/todo-app-chart/values.yaml
          git commit -m "Update tag in Helm chart"
          git push

  failure-notification:
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Notify on Failure
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: payalsharma19082004@gmail.com
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Deployment Failed"
          body: "The deployment of the Node.js application to Kubernetes has failed."
          to: ${{ secrets.NOTIFY_EMAIL }}
